feat: parse `MsgSoftwareUpgrade`
xrplevm/big-dipper-2.0-cosmos pull request #11
Opened 2024-12-19 14:56 UTC by obnol

# [TA-3816] parse `MsgSoftwareUpgrade`

### Changes
- Add parse `MsgSoftwareUpgrade` message

<img width="2044" alt="Screenshot 2024-12-19 at 15 55 54" src="https://github.com/user-attachments/assets/4a36ecf3-b5d6-4257-9d68-c84f770981d7" />

2024-12-20 09:40 UTC, AgustinMJ requested changes

2024-12-20 09:40 UTC, AgustinMJ commented on apps/web-xrplevm/src/components/msg/software/software_upgrade/index.tsx
A `packages/ui/screens/proposal_details/components/overview` hi ha fet un cas per `softwareUpgradeProposal`, potser renta més fer-ho servir, no estarà pillant el `type` bé.  Se'm fa una mica raro que `proposals` faci servir `transactions` i `message_contents`, no? Què opines? Com vegis, així tampoc està malament, potser queda rarillo el `with info` potser podria ser `with binaries:`

2024-12-23 13:17 UTC, obnol commented on apps/web-xrplevm/src/components/msg/software/software_upgrade/index.tsx
ho deixaria així haha

2024-12-24 11:23 UTC, AgustinMJ approved these changes

2024-12-24 11:24 UTC, merged