fix: xrpl-evm logo
xrplevm/big-dipper-2.0-cosmos pull request #8
Opened 2024-12-18 15:22 UTC by obnol

## fix: xrpl-evm logo

### Changes
- Remove unnecessary favicons
- Add favicon
- Add logo
- Fix network selector logo

2024-12-18 17:50 UTC, AgustinMJ approved these changes

2024-12-19 10:08 UTC, AgustinMJ requested changes
Queda rarete el logo tan gran en el loading, no? Estaria bé ficar-ho del mateix tamany que estava abans, que quedi el loading més o menys centrat

2024-12-19 10:47 UTC, obnol commented
> Queda rarete el logo tan gran en el loading, no? Estaria bé ficar-ho del mateix tamany que estava abans, que quedi el loading més o menys centrat

abans no hi havia logo realment

2024-12-19 15:39 UTC, AgustinMJ approved these changes

2024-12-19 15:40 UTC, merged